// vim: tw=79

= CRUD flows for ceph cluster entities

The ceph-integration module need to provide flows for creating, retrieving,
updating and deleting various entities like pools, rbds, ec-pools etc.

== Problem description

Currently the ceph-integration module provides flows only for creation and
deletion of storage pools. Need to add flows for managing rbds, osd, erasure
code profiles and ec-pools as well.

== Use Cases

CRUD operations for ceph cluster entities like storage pools, rbds, ec-pools and
erasure code profiles.

== Proposed change

Add flows in ceph-integration module for below

* Pool
** Create
** Update
** Delete

* RBDs
** Create
** Delete
** Resize

* Erasure coded pool
** Create
** Update
** Delete

* Erasure code profile
** Create
** Delete

=== Alternatives

There are two options to achieve the CRUD flows for ceph entities -

* Use Calamari REST endpoints
** pros
*** Currently Calamari supports create/update/delete REST end points for pool
management. For everything else, we need to invoke generic `CLI` end point from
Calamari

** cons
*** Introduces another daemon on cluster MON nodes

* Use direct rados and rnd command calls from ceph-integration modules
** pros
*** Doesn't need another daemon running on the MON nodes

** cons
*** None

=== Data model impact:

* Add models for
** RBDs
** Erasure coded pools
** Erasure code profiles

The snippet from definitions regarding the changes are as below

```
namespace.tendrl.ceph_integration:
  flows:
    .......
    CreateECProfile:
      atoms:
        - tendrl.ceph_integration.objects.ECProfile.atoms.create.Create
      help: "Create EC Profile"
      enabled: true
      inputs:
        mandatory:
          - ECProfile.name
          - ECProfile.k
          - ECProfile.m
        optional:
          - ECProfile.plugin
          - ECProfile.directory
          - ECProfile.ruleset_failure_domain
      run: tendrl.ceph_integration.flows.create_ec_profile.CreateECProfile
      type: Create
      uuid: faeab231-69e9-4c9d-b5ef-a67ed057f98d
    ......

  objects:
    Rbd:
      atoms:
        Create:
          enabled: true
          help: "Create rbd"
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
              - Rbd.size
          name: "Create Rbd"
          run: tendrl.ceph_integration.objects.Rbd.atoms.create.Create
          type: Create
          uuid: 7a2df258-9b24-4fd3-a66f-ee346e2e3720
        Delete:
          enabled: true
          help: "Delete rbd"
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
          name: "Delete Rbd"
          run: tendrl.ceph_integration.objects.Rbd.atoms.delete.Delete
          type: Delete
          uuid: 7a2df258-9b24-4fd3-a66f-ee346e2e3721
        Resize:
          enabled: true
          help: "Resize Rbd"
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
              - Rbd.size
          name: "Resize Rbd"
          run: tendrl.ceph_integration.objects.Rbd.atoms.resize.Resize
          type: Update
          uuid: 7a2df258-9b24-4fd3-a66f-ee346e2e3722
      flows:
        CreateRbd:
          atoms:
            - tendrl.ceph_integration.objects.Rbd.atoms.create.Create
          help: "Create Rbd"
          enabled: true
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
              - Rbd.size
          run: tendrl.ceph_integration.objects.Rbd.flows.create_rbd.CreateRbd
          type: Create
          uuid: 9bc41d8f-a0cf-420a-b2fe-18761e07f3d2
        DeleteRbd:
          atoms:
            - tendrl.ceph_integration.objects.Rbd.atoms.delete.Delete
          help: "Delete Rbd"
          enabled: true
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
          run: tendrl.ceph_integration.objects.Rbd.flows.delete_rbd.DeleteRbd
          type: Delete
          uuid: 4ac41d8f-a0cf-420a-b2fe-18761e07f3a7
        ResizeRbd:
          atoms:
            - tendrl.ceph_integration.objects.Rbd.atoms.resize.Resize
          help: "Resize Rbd"
          enabled: true
          inputs:
            mandatory:
              - Rbd.pool_id
              - Rbd.name
              - Rbd.size
          run: tendrl.ceph_integration.objects.Rbd.flows.resize_rbd.ResizeRbd
          type: Update
          uuid: 4ac41d8f-a0cf-420a-b2fe-18761e07f3c9
      attrs:
        name:
          help: Name of the rbd
          type: String
        size:
          help: Size of the rbd (MB)
          type: int
        pool_id:
          help: Id of the pool
          type: String
        order:
          help: Order of the rbd
          type: String
        block_name_prefix:
          help: Prefix for the block name
          type: String
        format:
          help: format of rbd
          type: int
        features:
          help: featutres for rbd
          type: list
        flags:
          help: flags for rbd
          type: list
      help: "Rbd"
      enabled: true
      value: clusters/$TendrlContext.integration_id/Pools/$Pool.pool_id/rbds/$Rbd.name
      list: clusters/$TendrlContext.integration_id/Pools/$Pool.pool_id/rbds
    ECProfile:
      atoms:
        Create:
          enabled: true
          help: "Create ec profile"
          inputs:
            mandatory:
              - ECProfile.name
              - ECProfile.k
              - ECProfile.m
            optional:
              - ECProfile.plugin
              - ECProfile.directory
          name: "Create ec profile"
          run: tendrl.ceph_integration.objects.ECProfile.atoms.create.Create
          type: Create
          uuid: 7a2df258-9b24-4fd3-a66f-ee346e2e3730
        Delete:
          enabled: true
          help: "Delete ec profile"
          inputs:
            mandatory:
              - ECProfile.name
          name: "Delete ec profile"
          run: tendrl.ceph_integration.objects.ECProfile.atoms.delete.Delete
          type: Delete
          uuid: 7a2df258-9b24-4fd3-a66f-ee346e2e3740
      flows:
        DeleteECProfile:
          atoms:
            - tendrl.ceph_integration.objects.ECProfile.atoms.delete.Delete
          help: "Delete ec profile"
          enabled: true
          inputs:
            mandatory:
              - ECProfile.name
          run: tendrl.ceph_integration.objects.ECProfile.flows.delete_ec_profile.DeleteECProfile
          type: Delete
          uuid: 4ac41d8f-a0cf-420a-b2fe-18761e07f3b9
      attrs:
        name:
          help: Name of the ec profile
          type: String
        k:
          help: k value for ec profile
          type: int
        m:
          help: m value for ec profile
          type: int
        plugin:
          help: ec profile plugin
          type: String
        directory:
          help: directory for ec profile
          type: String
        ruleset_failure_domain:
          help: rule set failure domain for ec profile
          type: String
      enabled: true
      list: clusters/$TendrlContext.integration_id/ec_profiles
      value: clusters/$TendrlContext.integration_id/ec_profiles/$ECProfile.name
      help: EC profile
    Pool:
      atoms:
        Create:
          enabled: true
          help: "Pool create Atom"
          inputs:
            mandatory:
              - Pool.poolname
              - Pool.pg_num
              - Pool.min_size
            optional:
              - Pool.type
              - Pool.erasure_code_profile
              - Pool.quota_enabled
              - Pool.quota_max_objects
              - Pool.quota_max_bytes
          name: "Create Pool"
          run: tendrl.ceph_integration.objects.Pool.atoms.create.Create
          type: Create
          uuid: bd0155a8-ff15-42ff-9c76-5176f53c13e0
        Delete:
          enabled: true
          help: "Pool delete Atom"
          inputs:
            mandatory:
              - Pool.pool_id
          name: "Delete Pool"
          run: tendrl.ceph_integration.objects.Pool.atoms.delete.Delete
          type: Delete
          uuid: 9a2df258-9b24-4fd3-a66f-ee346e2e3720
        Update:
          enabled: true
          help: "Pool update Atom"
          inputs:
            mandatory:
              - Pool.pool_id
            optional:
              - Pool.poolname
              - Pool.size
              - Pool.pg_num
              - Pool.quota_enabled
              - Pool.quota_max_objects
              - Pool.quota_max_bytes
          name: "Update Pool"
          run: tendrl.ceph_integration.objects.Pool.atoms.update.Update
          type: Update
          uuid: 9a2df258-9b24-4fd3-a66f-ee346e2e3721
      flows:
        DeletePool:
          atoms:
            - tendrl.ceph_integration.objects.Pool.atoms.delete.Delete
          help: "Delete Ceph Pool"
          enabled: true
          inputs:
            mandatory:
              - Pool.pool_id
              - TendrlContext.sds_name
              - TendrlContext.sds_version
              - TendrlContext.integration_id
          run: tendrl.ceph_integration.objects.Pool.flows.delete_pool.DeletePool
          type: Delete
          uuid: 4ac41d8f-a0cf-420a-b2fe-18761e07f3b9
        UpdatePool:
          atoms:
            - tendrl.ceph_integration.objects.Pool.atoms.update.Update
          help: "Update Ceph Pool"
          enabled: true
          inputs:
            mandatory:
              - Pool.pool_id
            optional:
              - Pool.poolname
              - Pool.size
              - Pool.pg_num
              - Pool.quota_enabled
              - Pool.quota_max_objects
              - Pool.quota_max_bytes
          run: tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool
          type: Update
          uuid: 4ac41d8f-a0cf-420a-b2fe-18761e07f3b2
      attrs:
        crush_ruleset:
          help: "The ID of a CRUSH ruleset to use for this pool. The specified ruleset must exist."
          type: Integer
        erasure_code_profile:
          help: "For erasure pools only.It must be an existing profile "
          type: String
        min_size:
          help: "sets the number of replicas for objects in the pool"
          type: Integer
        pg_num:
          help: "The total number of placement groups for placement purposes."
          type: Integer
        pgp_num:
          help: "The total number of placement groups for the pool."
          type: Integer
        pool_id:
          help: "id of the pool"
          type: Integer
        poolname:
          help: "Name of the Ceph pool"
          type: String
        type:
          help: "Type of the Ceph pool(ec or replicated)"
          type: String
        replica_count:
          help: "Replica count of volume"
          type: Integer
        size:
          help: "Sets the minimum number of replicas required for I/O"
          type: Integer
        quota_enabled:
          help: if quota enabled for the pool
          type: bool
        quota_max_objects:
          help: maximum no of object
          type: int
        quota_max_bytes:
          type: int
          help: "Pool"
      enabled: true
      value: clusters/$TendrlContext.integration_id/Pools/$Pool.pool_id
      list: clusters/$TendrlContext.integration_id/Pools
    .........
```

=== Impacted Modules:

==== Tendrl API impact:

TODO

==== Notifications/Monitoring impact:

* To be discussed in separate spec.
* RBD utilization monitoring

==== Tendrl/common impact:

None

==== Tendrl/node_agent impact:

None

==== Sds integration impact:

* ceph-integration module to add the required flows for CRUD operations on ceph
cluster entities

=== Security impact:

None

=== Other end user impact:

None

=== Performance impact:

None

=== Other deployer impact:

None

=== Developer impact:

None

== Implementation:

* Update data model for pool and add an attribute for type

```
class Pool(objects.CephIntegrationBaseObject):
    def __init__(self, pool_id=None, type=None
                 pool_name=None, pg_num=None, min_size=None,
                 used=None, percent_used=None, *args, **kwargs):
        super(Pool, self).__init__(*args, **kwargs)

        self.value = 'clusters/%s/Pools/%s'
        self.pool_id = pool_id
        self.pool_name = pool_name
        self.pg_num = pg_num
        self.min_size = min_size
        self.used = used
        self.percent_used = percent_used
        self.deleted = deleted
        self.type = type
        self.erasure_code_profile = erasure_code_profile
        self.quota_enabled = quota_enabled
        self.quota_max_objects = quota_max_objects
        self.quota_max_bytes = quota_max_bytes
        self._etcd_cls = _Pool
```

* Add data model for RBDs

```
class Rbd(objects.CephIntegrationBaseObject):
    def __init__(self, name=None, size=None,
                 pool_id=None, order=None,
                 block_name_prefix=None,
                 format=None, features=None,
                 flags=None,
                 *args, **kwargs):
        super(Rbd, self).__init__(*args, **kwargs)

        self.value = 'clusters/%s/Pools/%s/rbds/%s'
        self.name = name
        self.size = size
        self.pool_id = pool_id
        self.order = order
        self.block_name_prefix = block_name_prefix
        self.format = format
        self.features = features
        self.flags = flags
        self._etcd_cls = _Rbd
```

* Add data model for ec profile

```
class ECProfile(objects.CephIntegrationBaseObject):
    def __init__(self, name=None, k=None,
                 m=None, plugin=None,
                 directory=None,
                 ruleset_failure_domain=None,
                 *args, **kwargs):
        super(ECProfile, self).__init__(*args, **kwargs)

        self.value = 'clusters/%s/ec_profiles/%s'
        self.name = name
        self.k = k
        self.m = m
        self.plugin = plugin
        self.directory = directory
        self.ruleset_failure_domain = ruleset_failure_domain
        self._etcd_cls = _ECProfile
```

* Add flows for pool management. This should support ec-pools as well inherently
** Create
** Delete
** Update

* Add flows for RBDs management
** Create
** Resize
** Delete

* Add flows for ec profile management
** Create
** Delete

=== Assignee(s):

Primary assignee:
  shtripat

Other contributors:
  NA

=== Work Items:

* https://github.com/Tendrl/specifications/issues/126

== Dependencies:

* If calamari options is selected for CRUD operations on entities, there is a
dependency on Calamari and it should be running on MON nodes

== Testing:

* Verify the below scenarios
** Create storage pool
** Update storage pool details
** Delete storage pool
** Create ec-pool
** Update ec-pool details
** Delete ec-pool
** Create RBD associated to a pool
** Update details of the RBD
** Delete RBD
** Create ec-profile
** Delete ec-profile
** Listing of pools, RBDs (under specific pool), ec-profiles (under cluster)

== Documentation impact:

None

== References:

None
