// vim: tw=79

= Tendrl Ceph-installer Wrapper

Ceph-installer allows the administrator to provision and control the deployment
of Ceph clusters via a RESTFul API. Tendrl expected to make use of these APIs for provisioning the Ceph clusters.

== Problem description

Ceph-installer provides a set of Rest APIs which allows one to install and configure Ceph.Ceph-installer make use of ceph-ansible (ansible based deployment tool for provisioning ceph) internaly and exposes the Rest APIs that accepts and returns JSON responses with meaningful error codes and messages.  Tendrl is expected to perform Ceph deployment and planning to leverage the capabilities of ceph-installer by writing a wrapper for integration.

== Use Cases

* Creating the ceph cluster
  ** Install the packages
  ** Configure MONs and OSDs
* Expanding the ceph cluster
  ** Install Packages(if a new host is added)
  ** Configure MONs and OSDs
* Task management
  A task is created when an action on a remote node is triggered. Tasks are used to track the progress of the operation.

== Proposed change

A wrapper needs to be created which abstracts the capabilities provided by the ceph-installer.

=== Flows and atoms

* Create ceph cluster
  ** Package installation
  ** Configure MONs
  ** Configure OSDs
  ** Check task status

* Expand ceph cluster
  ** Add OSD
  ** Add a new node
  ** Check task status

=== Alternatives

None.

=== Data model impact:

None.

=== Impacted Modules:

==== Tendrl API impact:

Tendrl API provides an interface to create a Ceph cluster.

Sample JSON

----------
POST '/api/v1/CreateCluster'


----------

Sample Response

----------
Status: 202 Accepted
{ job_id: "5540ca6d-378c-4ce2-b632-46a43c5de835" }
----------

==== Tendrl/node_agent impact:

Since ceph installer does not support operating from a node inside the cluster,
the node agent running on the API node needs to be designated as a provisioner
for ceph cluster. This would be accomplished by adding a tag for
`provisioners/ceph`. The API would route jobs directly to this tag, with an
empty `node_ids` array in the job payload.

The following job parameters would be implemented:

  {
    "integration_id": "9a4b84e0-17b3-4543-af9f-e42000c52bfc",
    "run": "tendrl.flows.CreateCluster",
    "status": "new",
    "type": "node",
    "sds_type": "ceph",
    "sds_version": "10.2.5",
    "name": "MyCluster",
    "node_ids": [],
    "tags": ["provisioner/ceph"],
    "parameters": {
      "TendrlContext.integration_id": "9a4b84e0-17b3-4543-af9f-e42000c52bfc",
      "Node[]": ["3943fab1-9ed2-4eb6-8121-5a69499c4568"],
      "node_configuration": {
        "3943fab1-9ed2-4eb6-8121-5a69499c4568": {
          "role": "ceph/osd",
          "journal_size": 5192,  # Megabytes
          "journal_colocation": "false",
          "storage_disks": [
            {
              "device": "/dev/sda",
              "journal": "/dev/sdc"
            },
            {
              "dev_name": "/dev/sdb",
              "journal": "/dev/sdc"
            }
          ]
        }
      }
    }
  }

The validations to be carried out on these parameters are as follows, when the
role of a node is `ceph/osd`:

* `journal_size` is optional. Value should be in Megabytes.
* `journal_colocation` is optional and value should be a boolean.
* `storage_disks` is mandatory. If not provided, it's an error because the node
  cannot be part of the cluster as an osd node.
** It has to be an array.
** It has to contain hashes.
** Each hash has to contain a `device` key.
*** If `journal_colocation` is set to `true` _for the node_, the `journal` key
    cannot exist in the hash
*** If `journal_colocation` is set to `false` _for the node_, the `journal` key
    must contain a device
** Every device path specified in either the `device` or the `journal` key must
   be a valid block device on the node
** A device cannot be listed under both `device` and `journal` (across multiple
   hashes), per host

The following journal configurations are valid:

Dedicated journal::
Different values for `device` and `journal`.

Co-located journal::
Only the `device` value.

Multi-journal (implies dedicated journals)::
Same `journal` device specified for multiple devices.

== Implementation:

* https://github.com/Tendrl/specifications/issues/48

=== Assignee(s):

Primary assignee:

nthomas-redhat

Other contributor(s):

=== Work Items:

* https://github.com/Tendrl/ceph-integration/issues/106
* https://github.com/Tendrl/node-agent/issues/202

== Dependencies:


None.


== Testing:

End users can't directly test this feature, however the flows like ceph cluster creation and expansion will use this feature internally.


== Documentation impact:

None.


== References:

* http://docs.ceph.com/ceph-installer/docs/
