= Enable gluster native events in tendrl

Events generated by glusterfs events API should be exposed by tendrl.


== Problem description

Currently tendrl is not utilizing the events exposed by glusterfs events API.
Tendrl should be enhanced to consume and handle the events.

== Use Cases

* Glusterfs events API pushes events for certain internal glusterfs failure conditions
which is not track able by tendrl. Tendrl can raise suitable alerts for such events.

* The interval of sds state sync can be increased (to 30 min) and we should have event
driven state sync. which will considerably increase the efficiency of gluster integration
service.

== Proposed change

The event receiver web-hook can be run on all the gluster storage nodes as a
thread/greenlet in gluster-integration daemon. And we should configure the
gluster eventing daemon to push events in localhost mode (the events generated
by gluster eventing daemon will be pushed to the web-hook running only on
that particular node). With this we are eliminating single point of failure
w.r.t event listener.

Since some of the events are raised from all the nodes or raised multiple times
(till alert condition gets fixed), tendrl should make sure that duplicate events
are handled appropriately by checking the state information stored in etcd.

In future, gluster integration state sync should be based on events received
by glusterfs events API. Thus we make sure that we do the state sync only when
there is a state change. Also we can have a 30 min sync, to make sure that we
have a valid state in case events are missed.

=== Alternatives

An alternate approach to listen events is to have listener enabled in only one of
the gluster-integration process, and configure all gluster events API to push
events to this instance. Though this has slight advantage of not having to run the
event listeners on all the nodes.

The main problem with this approach is handling the failure of this listener node.
we would have to move the listener to another storage node. There would be certainly
a gap during which we would not have any listeners running which would lead to event
loss.

=== Data model impact

No data model impact, the event handlers should convert the gluster native Events to
a format that is in line with the tendrl event model.

=== REST API impact

None

=== Security impact

None

=== Notifications/Monitoring impact

With this spec tendrl will be able to send alerts/notifications based on the gluster
native events.

=== Other end user impact

Users will be receiving events/alerts that are raised by glusterfs events API, based on
the alerts/notification configuration in tendrl

=== Performance Impact

We would need to run a new thread/greenlet in gluster-integration process to listen
to the native events. Performance evaluation has to be made after adding listener to
gluster integration process.

On the other hand, if we increase the gluster integration sds sync interval to (say
30 mins) and have the sync driven by events. There will be a considerable improvement
in the performance.

=== Other deployer impact

We would need to install an additional package glusterfs-events on all the storage
nodes and this daemon has to be started and configured as part of import cluster
flow.

=== Developer impact

None

== Implementation

=== Assignee(s)

nnDarshan

Primary assignee:
nnDarshan

Other contributors/reviewers:
  aravinda, shubhendu, tendrl-core

=== Work Items

Would be better if we can implement this in multiple phases:

* Phase 1:
  	As part of import cluster the eventing rpm has to be installed and configured to
push events to the locally running receiver in gluster integration. We get a list of
pre difined alerts from gluster team and write listeners to blindly convert these to
tendrl alerts and which in turn will trigger notifications if configured.

* Phase 2:
        Add logic to correlate the gluster native events i.e write suitable event handlers
which checks the current state and then raise alerts/events to make sure that tendrl
doesn't raises duplicate alerts.

* Phase 3:
        Make gluster-integration sds sync event driven i.e we increase the sync interval
to a bigger value(say 30 mins) and perform sync only when gluster integration gets some
gluster native event which might be because of state change.

== Dependencies

* Get complete list of all supported events from glusterfs team

* Get a list of alerts among all events from glusterfs team, these alerts
will be used in phase 1

== Testing

* Make sure that there is no great performance degradation after implementing this spec,
as this spec involves addition of a new thread to gluster-integration process

* Make sure all types of events are handled appropriately by tendrl

* After phase 2 duplicate events sent by glusterfs events should be handled properly

== Documentation Impact

None

== References

https://github.com/Tendrl/specifications/issues/180
