// vim: tw=79

= Tendrl Definitions: Display list of hosts discovered by Tendrl

Display list of hosts discovered by Tendrl, whether they currently associated with a cluster or not. The list should have functionality for 

* filtering by name, cluster, role and status.
* sorting by name.

Host list will be sorted by name by default.

== Problem description

Tendrl should show list of hosts discovered by Tendrl along with their details.

The details shown for each host in UI is -

* Host Name
* Status
* IP Address
* Storage Usage
* CPU Utilisation
* Memory Usage
* Cluster Name
* Role
* Alert Count

== Use Cases

Users can see the list of host present in Tendrl. They can also 

* filter by name, cluster, role and status.
* sort by name.

As per the API support, users can 

* filter by name and cluster
* sort by name

== Proposed change

* Create a view for listing host details.
* For showing storage usage, cpu utilisation and memory usage, use donut chart component.
* Implement client side filer and sorting functionality using angular's filter and orderby components.
* Send polling call after 2 minutes to get the updated data.
* Show total count of hosts present discoverable by Tendrl.

=== Alternatives

Generate list component can be created and used for listing the host. But because of its complexity and time constraint, we will pick this up later.

=== Data model impact:


=== Impacted Modules:

==== Tendrl API impact:

/api/1.0/GetNodeList - fetch the list of host

API support present for -

* Host Name
* IP Address
* Storage Usage
* CPU Utilisation
* Memory Usage
* Alert count

Required from Api - 

* response format for the API call
* polling API call and its response format	

==== Notifications/Monitoring impact:

Required from monitoring stack: response format for monitoring data

==== Tendrl/common impact:

==== Tendrl/node_agent impact:

==== Sds integration impact:

=== Security impact:

=== Other end user impact:

None

=== Performance impact:

None

=== Other deployer impact:

None

=== Developer impact:

None

== Implementation:


=== Assignee(s):

Primary assignee:
  kamleshverma1

Other contributors:
  None
  
=== Work Items:

https://github.com/Tendrl/tendrl_frontend/issues/66

== Estimate

Template creation, sort and filter functionality implementation - 2 day

API integration - 1 day

Unit testing - 1 day

Worst-case scenario - can extend to 5 days

== Dependencies:

https://github.com/Tendrl/tendrl_frontend/issues/67

https://github.com/Tendrl/documentation/pull/62

https://github.com/Tendrl/specifications/issues/79

== Testing:

Test whether hosts are correctly being displayed or not.

== Documentation impact:

None

== References:

https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/199053039

https://github.com/Tendrl/specifications/issues/75
