// vim: tw=avored-markdown/preview.ht79

# Changes in tendrl modules after introduction of new logging framework

Since a new logging framework is being introduced (https://github.com/Tendrl/specifications/pull/94), after its implementation
there will be requirement of changes in all the modules of Tendrl where logging is used.
This file proposes all those changes and how they will be made.


## Problem description

Many modules in Tendrl have a functionality of logging different types of situations/use cases such as logging (info, errors, warning etc.).
Till now these were implemented by importing the Python standard library's logging module then calling logger functions to handle the logging.
After implementation of new logging framework there will be requirement of changes in all the modules of Tendrl where logging is used.

#### Use Cases

Logs and job operations need be treated as messages.

#### Proposed change

* *Importing logging and calling logger functions* will be replaced by:
** Import Message and Event class from commons.
** Create a Message object by passing the required arguments to it and then
 pass this message object to the event class
** There will be 3 arguments that will be mandatory to create the Message
object:
 *** priority
 *** publisher
 **** eg. CEPH-INTEGRATION, GLUSTER-INTEGRATION, NODE-AGENT, PERFORMANCE-MONITORING
 *** payload   <Json>
 *** If the message is for operation updates the job_id will also be an mandatory parameter.
** If an Exception has to be passed with the message then the ExceptionMessage object has to be passed to the Event class, not the Message object.

#### Alternatives

None

#### Data model impact:

None

#### Impacted Modules:

#### Tendrl/common impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Tendrl/node_agent impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Tendrl/gluster_integration impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Tendrl/ceph_integration impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Tendrl/alerting impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Tendrl/performance_monitoring impact

All the logging instances to be replaced by the new framework as mentioned in proposed change.

#### Security impact:
None

#### Notifications/Monitoring impact

None

#### Other end user impact:

None

#### Performance impact:

None

#### Other deployer impact:

None

#### Developer impact:

None

#### Implementation:
* Import Message or ExceptionMessage class from commons.
* Import Event class from commons
* Create a message object.
* Pass the message object as an argument to initialize Event class.
----
from tendrl.commons.event import Event
from tendrl.commons.message import ExceptionMessage
from tendrl.commons.message import Message

Event(
    Message(
        priority="priority",
        publisher=NS.publisher_id, # Defined component wise
        payload={"message": "message"}
        job_id ="job_id"
    )
)

Event(
    ExceptionMessage(
        priority="priority",
        publisher=NS.publisher_id,
        payload={"message": "error",
                 "exception": ex
                 }
    )
)
----

#### Assignee(s):

Primary assignee: anmolsachan

Other contributors:

#### Work Items:


#### Dependencies:

https://github.com/Tendrl/specifications/pull/94

#### Testing:


#### Documentation impact:

None

#### References:

* https://github.com/Tendrl/specifications/pull/94
* https://github.com/Tendrl/specifications/issues/55
* https://github.com/Tendrl/specifications/blob/master/specs/pluggable_alert_delivery.adoc
* https://github.com/Tendrl/node-agent/issues/192
