= Pluggable Alerts Delivery End-Points

== Introduction

The alerting module in tendrl needs to alert/notify

* State changes of tendrl managed entities
* Threshold breaches of utilizations of tendrl managed entities.

via mediums such as:

* SNMP-traps
* email

== Problem description

* The different tendrl supported alerting means need to be pluggable in the
  sense that adding any new alert notifying means should be an easy task and
  should not involve much changes in the core alerting framework.
* The alerting mechanism should have a way to set importance of alerts so that
  the alerts desingated as important will be notified to users even if the
  alerting module crashed and hence the alert could not be notified but will
  be alerted once the alerting module is started back.

== Use Cases

* Dynamic addition of new means of notifying an alert.

== Proposed change

* Handlers will be defined in alerting module for dispatching observed alerts
  to configured destinations through respective means.
  ** Example: mail handler for sending out mail and snmp handler for snmp-trap
* A new handler can be hooked into the tendrl alerting system by adding it to
  a designated directory and with a name prefixed with the notification medium
  name. ex: email_handler for alerting/tendrl/alerting/notification/
* Whenever a new handler is added, the first thing the handler is supposed to
  do is add itself as a means to list of supported notification mechanisms in
  etcd.
* The alerts raised are persisted in etcd before sending out notifications in
  '/alerts' directory of etcd by node-agent.
* Each alert will carry an additional attribute that carries its significance
  which will be added by the respective handler. The supported significance
  levels can be 'HIGH', 'MEDIUM' and 'LOW'.
  ** The 'LOW' significance level alerts will not be notified. But will feature
     in the list of alerts in etcd.
  ** The 'MEDIUM' significance level alerts will be attempted to be notified.
  ** The 'HIGH' significance level alerts will be re-attempted to be notified
     (on restart) if a previous attempt failed(crash of alerting service).

----
  Note:
    * The different alerts need to be yet classified on various importance
      levels.
      And this is my current opinion:
      **  Any threshold breach corresponding notification is a 'HIGH'
          significance alerts
    * The complete list of events and their importance/significance level needs
      to be decided.Following are some of the github issues to capture the list
      ** https://github.com/Tendrl/documentation/issues/44
      ** https://github.com/Tendrl/documentation/issues/45
      ** https://github.com/Tendrl/documentation/issues/46
----

* The alerts marked as significance HIGH are deemed important and hence their
  delivery is guranteed even in case of sudden crash of alerting module. This
  is achieved by updating a field('notified': True) of the alert in etcd
  directory to indicate that the alert has been notified. When alerting module
  is started, it scans all alerts in '/alerts' directory and sends out
  notifications for those that are marked significance 'HIGH' and are not set
  with 'notified': True.
* So this means 2 flows need to be added:
  ** For users to be able to subscribe to receive different types of alerts of
     different entities along with configuration for chosen ways of being
     alerted.
  ** For listing the supported notification mechanisms.
  And correspondingly the tendrl-api will have apis for these.

=== Alternatives

To be explored.

=== Data model impact

The structure of alert can be the following:

----
{
  'event-id': <unique tendrl generated id>,
  'node-id': <id of node on which alert was detected>,
  'time-stamp': <time stamp of alert>,
  'resource': <the name of resource for which alert has been raised>,
  'current-value': <the current observed value status/utilization as applies>
  'tags': <custom alert specific info>,
  'type': <the type of alert percent-used/status of resource>
  'severity': <severity of alert>
  'significance': <the severity of importance of notifying the alert>
}
----

ex:
For a performance monitoring related alert:

----
{
  event_id : '6405962e-bc46-11e6-a4a6-cec0c932ce01',
  node_id: '5205962e-bc46-11e6-a4a6-cec0c932cz01',
  time_stamp: '1481046935.536',
  'resource': 'memory',
  'CurrentValue': '7.176942e+00',
  tags: {
    'WarningMax': '1.000000e+00',
    'FailureMax': '2.000000e+00',
  },
  'Type': 'percent-used',
  'severity': 'Critical',
  'significance': 'HIGH',
}
----

and for a status based alert:

----
{
  event_id : '6405962e-bc46-11e6-a4a6-cec0c932ce01',
  node_id: '5205962e-bc46-11e6-a4a6-cec0c932cz01',
  time_stamp: '1481046935.536',
  'resource': 'cluster',
  'CurrentValue': 'Down',
  tags: {
    'cluster_id' : '6406062e-be46-11e6-a4a6-cec0c932ce01',
  },
  'Type': 'status',
  'severity': 'Critical',
  'significance': 'HIGH',
}
----

The severity levels can be 'Critical', 'Info' or 'Warning'.

=== Impacted Modules:

==== Tendrl API impact:

tendrl/api parses the definitions file for dynamic generation of apis. Hence
an impact of this change on api needs to be studied.

==== Notifications/Monitoring impact:

The alerting application needs to add flows for configuring users.

==== Tendrl/common impact:

None

==== Tendrl/node_agent impact:

None

==== Sds integration impact:

None

=== Security impact:

None

=== Other end user impact

New apis will be added for user configuration.

=== Performance impact

None

=== Other deployer impact

None


=== Developer impact

== Implementation

=== Assignee(s)

Primary assignee:

  * Changes in alerting module : Anmol Babu

== Dependencies:

* User management in tendrl.

== Documentation impact

* This adds 2 apis:
  ** One to list supported alert notifying mechanisms.
  ** One for Users to subscribe to interested alerts and be notified by chosen
     alerting means.

== Testing

This adds new apis for user configuration which need to be tested.

== References

* Comments on https://github.com/Tendrl/alerting/pull/1
* https://github.com/Tendrl/documentation/issues/44
* https://github.com/Tendrl/documentation/issues/45
* https://github.com/Tendrl/documentation/issues/46
