= Pluggable Alerts Delivery End-Points

== Introduction

The alerting module in tendrl needs to alert/notify

* State changes of tendrl managed entities
* Threshold breaches of utilizations of tendrl managed entities.

via mediums such as:

* SNMP-traps
* email

== Problem description

The different alert delivery options like email, snmp-traps, etc.. need to be
configurable i.e, some users might choose to receive only email alerts whereas
some might choose all the mediums that the tendrl supports. This creates a
requirement for the alert delivery mechanism to be configurable.

== Use Cases

Users configured in tendrl subscribe to specific types of alerts and need to
be notified only through chosen mediums of alert delivery.

* User A wants to be notified of all tendrl supported alerts of entities of
  cluster C1 and C2 via email and snmp. User B wants to be notified of all
  alerts of cluster C3 only via email.
* User A wants to be notified of all tendrl supported alerts of entities of
  cluster C1 via email and C2 via snmp traps.
* User A wants to be notified only of cpu and disk utilization threshold
  breaches and node status changes via only sms.

And all combinations of the above.

== Proposed change

* Tendrl managed users will be allowed to subscribe for specific alerts or all
  alerts via tendrl-api. This api will require the details like what kinds of
  alerts the user desires to be notified of, the medium through which user
  desires to be notified.The appropriate validations will be made as part of
  execution of the api job to find if all required configurations are present
  for the choices made in api request body.

----
  ex
      {
        name: User1,
        is_admin: False,
        email: user1@users.com,
        alert_subscriptions: [
          {
            cluster_name: 'cluster-1',
            alert_categories: ['cpu_utilization', 'cluster_utilization']
            notification_medium: ['email', 'snmp']
          },
          {
            cluster_name: 'cluster-2',
            alert_categories: '*',
            notification_medium: ['email', 'snmp']
          }
        ]
      }
----

* A user can be marked as admin by setting is_admin to True. The admin user
  needs to be configured with some details like below:
  For email notification,
  ** email-id
  ** encrypted password/auth cert file
    *** Optional if auth required, in most enterprises its likely not
  ** Authentication protocol ssl/tls if authentication required.
  ** smtp email server and port.
  ** If any of the necessary configuration is missed, configuring corresponding
     means of notification(email/snmp) will not be allowed for other users and
     hence such a means of notification will not be available.
     *** Example: If admin user is not configured with snmp port and server,
     then the email notification will not be available and also the other users
     will not be allowed to subscribe for email notifications.
  This configuration will be done via an api exposed by tendrl-api and the
  validations of api request body will be done by the api's corresponding flow.

=== Alternatives

To be explored.

=== Data model impact

The user management capability needs to be built into tendrl.
Till then these configurations can be maintained as part of the config file as
below:

----
[alerting]
admin_email_id = abc@users.com
admin_email_smtp_port = 25
admin_email_smtp_server = smtp.xyz.abc.com
recipient_email_id = def@users.com
recipient_alert_subscriptions = *
recipient_notification_medium = ['email']
----

If client needs to be authenticated, user needs to specify authentication cert
file path as below:

----
[alerting]
admin_email_id = abc@users.com
admin_email_smtp_port = 25
admin_email_smtp_server = smtp.xyz.abc.com
admin_auth_cert = '<cert_path>'
recipient_email_id = def@users.com
recipient_alert_subscriptions = *
recipient_notification_medium = ['email']
----

The alert for performance threshold breaches as obtained from collectd looks
like below:

{
  'CurrentValue': '7.176942e+00',
  'WarningMax': '1.000000e+00',
  'Severity': 'FAILURE',
  'Plugin': 'memory',
  'TypeInstance': 'used',
  'DataSource': 'value',
  'FailureMax': '2.000000e+00',
  'Time': '1481046935.536',
  'Type': 'percent'
}

where the fields correspond to the following below:
* CurrentValue :
    The current utilization value.
* WarningMax
    The configured warning threshold on crossing which warning alert is raised.
* Severity
    The severity level of the threshold breached.
* Plugin
    The name of the plugin(same as the type of resource) for which the alert
    has been raised.
* TypeInstance
    The type of metric ex: used, available or total
* FailureMax
    The configured critical/failure threshold
* Time
    The time at which threshold breach was detected
* Type
    The type of value which breached the threshold.
    ex: percent to indicate it was the percentage value that breached threshold

The structure of alert has been modified to the following to suit any kind of
alerts as for a performance statistics threshold crossing:

----
{
  event_id : '6405962e-bc46-11e6-a4a6-cec0c932ce01',
  node_id: '5205962e-bc46-11e6-a4a6-cec0c932cz01',
  time_stamp: '1481046935.536',
  'resource': 'memory',
  'CurrentValue': '7.176942e+00',
  tags: {
    'WarningMax': '1.000000e+00',
    'FailureMax': '2.000000e+00',
  },
  'Type': 'percent-used',
  'severity': 'failure',
}
----

and for a status based alert:

----
{
  event_id : '6405962e-bc46-11e6-a4a6-cec0c932ce01',
  node_id: '5205962e-bc46-11e6-a4a6-cec0c932cz01',
  time_stamp: '1481046935.536',
  'resource': 'cluster',
  'CurrentValue': 'Down',
  tags: {
    'cluster_id' : '6406062e-be46-11e6-a4a6-cec0c932ce01',
  },
  'Type': 'status',
  'severity': 'failure',
}
----

=== Impacted Modules:

==== Tendrl API impact:

tendrl/api parses the definitions file for dynamic generation of apis. Hence
an impact of this change on api needs to be studied.

==== Notifications/Monitoring impact:

The alerting application needs to add flows for configuring users.

==== Tendrl/common impact:

None

==== Tendrl/node_agent impact:

None

==== Sds integration impact:

None

=== Security impact:

None

=== Other end user impact

New apis will be added for user configuration.

=== Performance impact

None

=== Other deployer impact

None


=== Developer impact

== Implementation

* Handlers will be defined in alerting module for dispatching observed alerts
  to configured destinations through respective means.
  ** Example: mail handler for sending out mail and snmp handler for snmp-trap
* A new handler can be hooked into the tendrl alerting system by adding it to
  a designated directory and with a name prefixed with the notification medium
  name. ex: email_handler for alerting/tendrl/alerting/notification/
* Whenever a new handler is added, the first thing the handler is supposed to
  do is add itself to a list of supported notification mechanisms in etcd.
* For the api to get list of the supported notification mechanisms, it can
  look into this list.
* Tendrl/alerting will look into user's 'notification_medium' field and
  accordingly:
  ** If tag is not present or its value is empty, it is interpreted as user
     having chosen not to receive any notification.
  ** The presence of valid values like 'email' or 'snmp', the appropriate
     notification handler(ex:mail_handler) is invoked to send out alerts.
* So this means 2 flows need to be added:
  ** One for users subscribing to receive different types of alerts of
     different entities.
  ** And one for listing the supported notification mechanisms.

=== Assignee(s)

Primary assignee:

  * Changes in alerting module : Anmol Babu

== Dependencies:

* User management in tendrl.

== Documentation impact

* This adds 2 apis:
  ** One to list supported alert notifying mechanisms.
  ** One for Users to subscribe to interested alerts and be notified by chosen
     alerting means.

== Testing

This adds new apis for user configuration which need to be tested.

== References

Comments on https://github.com/Tendrl/alerting/pull/1
