// vim: tw=79

= Tendrl Definitions: Display list of pool present in Ceph cluster in Tendrl

Display list of pool associated with a ceph cluster present in Tendrl. The list should have functionality for 

* filtering by pool name, cluster name, status and type.
* sorting by pool name.

Pool list will be sorted by name by default.

== Problem description

Tendrl should show list of pool associated with a ceph cluster along with their details.

The details shown for each pool in UI is -

* Pool Name
* Status
* Cluster Name
* Pool Type
* Pool Utilisation
* Replicas
* OSDs
* PGs
* Quotas
* Active alerts

== Use Cases

Users can see the list of pool associated with a ceph cluster present in Tendrl. They can also 

* filter by pool name, cluster name, status and type.
* sort by pool name, cluster name, pool utilization, and status.

As per API support, users can 

* filter by pool name, cluster name and status.
* sort by pool name, cluster name, pool utilization, and status.

== Proposed change

* Create a view for listing pool associated with a ceph cluster.
* For pool utilisation, use donut chart component.
* Implement client side filter and sorting functionality using angular's filter and orderby components.
* Send polling call after 2 minutes to get the updated data. 
* Show total count of pools present in a ceph cluster.

=== Alternatives

Generate list component can be created and used for listing the pool. But because of its complexity and time constraint, we will pick this up later.

=== Data model impact:


=== Impacted Modules:

==== Tendrl API impact:

/api/1.0/GetPoolList - fetch the list of pool

API support present for -

* Pool Name
* Status
* Cluster Name
* Pool Utilisation
* Replicas
* OSDs
* PGs

Required from API - 

* response format for the API call
* polling API call and its response format	

==== Notifications/Monitoring impact:

Monitoring data is not available at this point in time.

==== Tendrl/common impact:

==== Tendrl/node_agent impact:

==== Sds integration impact:

=== Security impact:

=== Other end user impact:

None

=== Performance impact:

None

=== Other deployer impact:

None

=== Developer impact:

None

== Implementation:


=== Assignee(s):

Primary assignee:
  gnehapk

Other contributors:
  None
  
=== Work Items:

https://github.com/Tendrl/tendrl_frontend/issues/66

== Estimate

Template creation, sort and Filter functionality implementation - 2 day

API integration - 1 day

Unit testing - 1 day

Worst-case scenario - can extend to 5 days

== Dependencies:

https://github.com/Tendrl/tendrl_frontend/issues/67

https://github.com/Tendrl/documentation/pull/62

== Testing:

Test whether pools present in a ceph cluster are correctly being displayed or not.

== Documentation impact:

None

== References:

https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417118
https://github.com/Tendrl/specifications/issues/75
