= Tendrl ansible to install grafana

Needs ansible playbook scripts for automatic installation and configuration of
grafana and tendrl metrics in the tendrl server.


== Problem description

Grafana will be used in tendrl to trigger alerts and visualize the tendrl
metrics. Currently, Tendrl-ansible is used to install and configure tendrl
packages. It should also support installation and configuration of tendrl
metrics and grafana package installation.
This specification provides the required changes in tendrl-ansible tool to
support installation and configuration of tendrl metrics and grafana.


== Use Cases

* Provide playbook for tendrl-ansible to install monitoring_integrtaion and grafana
along with server installation.


== Proposed change

* Add the repo to install latest grafana and its dependencies

* Install monitoring_integrtaion, grafana and
  also install grafana dependencies fontconfig, freetype* and urw-fonts

* Configure monitoring_integrtaion and  grafana
  This should add the required environment variables, set log path, database
  connection details, data source and the node details

  Sample default configuration:

```
  grafana_config:
    grafana_database:
      type: graphite
      host: <ip:port>
      name: grafana
      user: root
      password: ""

  Server Configuration Details:
    grafana_server:
      protocol: http

      # The ip address to bind to, empty will bind to all interfaces
      http_addr: ""
      http_port: 3000
      domain:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
      # binary where the static files are placed, public: html/js/css
      static_root_path: public
      # SSL cert & key file if grafana_server_protocol is https
      cert_file: ""
      cert_key: ""

  grafana_session:
      # Session provider could be either memory, file mysql. The default is "memory"
      grafana_session_provider: file
      session life time, default is 86400
      session_life_time: 86400
```

* Enable monitoring_integrtaion and grafana server to start at boot time

* Start the grafana-server service

* Document the ansible playbook configuration details in wiki


=== Alternatives

None

=== Data model impact

None

=== Impacted Modules:

==== Tendrl Ansible impact:

* Update roles in site.yml.sample about the repo details install grafana
and its dependencies for tendrl-server host installation.
- hosts: tendrl-server
  ```
  roles:
    - tendrl-copr
    - grafana
    ...
  ```

* Add repo details under tendrl-ansible/roles
  files directory with keys and the repo files
  tasks to install the repos

* Create and add tasks to install grafana and tendrl metrics packages
  in tendrl-ansible/roles/tasks

* Include tasks to configure grafana and tendrl metrics packages
  in tendrl-ansible/roles/tasks

* Update tendrl-ansible/roles/tendrl-server/handlers/main.yml
  to check the status of grafana server service and start

Sample playbook:

```
    name: Install Grafana package
        yum:
            name: "{{ grafana_pkg }}"
            state: present

    name: Configure Grafana
       template:
           src: grafana.ini.tendrl
           dest: /etc/grafana/grafana.ini

    name: Restart grafana
        service:
            name: grafana-server
            state: restarted

    name: Make sure grafana service is enabled and running
        service:
	    name: grafana-server
	    enabled: yes
	    state: running

```

==== Tendrl API impact:

None

==== Notifications/Monitoring impact:

None

==== Tendrl/common impact:

None

==== Tendrl/node_agent impact:

None

==== Sds integration impact:

None

==== Tendrl Dashboard impact:

None

=== Security impact:

None

=== Other end user impact:

None

=== Performance impact:

None.

=== Other deployer impact:

None.

=== Developer impact:

None.


== Implementation:

https://github.com/Tendrl/tendrl-ansible/issues/18

=== Assignee(s):

Primary assignee:
  Timothy Asir Jeyasingh
  Martin Bukatovič


=== Work Items:

* https://github.com/Tendrl/specifications/issues/175


== Dependencies:

None


== Testing:

* Verify that installation and configuration of grafana and tendrl metrics

* Verify the metrics graphs are showing properly and periodically


== Documentation impact:

None


== References:

None
