= Validation for volume creation

This spec specifies the host validation needed before volume creation

== Problem description

This spec specifies the host validation needed before volume creation.
Given a volume to be created with distribute count and replica count
what are the possible number of host that is needed to be created and
minimum number of brick in them to create the specified volume

== Use Cases

* This will be refered by UI developpers for validating host selection
during volume creation.

== Proposed change

The UI should matintain the json given below and use it for host validation.

----
{
    "2_1" : {
	2: [
	    [1,1]
	]
    },
    "2_2" :{
	2: [
	    [2,2],
	],
	3: [
	    [2,1,1],
	],
	4: [
	    [1,1,1,1],
	],
    }
    "2_3": {
	2: [
	    [3,3],
	]
	3: [
	    [3,2,1],
	    [2,2,2],
	],
	4: [
	    [3,1,1,1],
	    [2,2,1,1],
	],
	5: [
	    [2,1,1,1,1],
	],
	6: [
	    [1,1,1,1,1,1],
	],
    },
    "2_4": {
	2: [
	    [4,4],
	],
	3: [
	    [4,3,1],
	    [3,3,2],
	    [4,2,2],
	],
	4: [
	    [4,2,1,1],
	    [3,3,1,1],
	    [3,2,2,1],
	    [2,2,2,2],
	]
	5: [
	    [4,1,1,1,1],
	    [3,2,1,1,1],
	    [2,2,2,1,1],
	],
	6:[
	    [3,1,1,1,1,1],
	    [2,2,1,1,1,1],
	]
	7:[
	    [2,1,1,1,1,1,1],
	],
	8:[
	    [1,1,1,1,1,1,1,1],
	]
    }
    "3_1": {
	3 : [
	    [1,1,1],
	],
    }
    "3_2": {
	3 :[
	    [2,2,2],
	],
	4 :[
	    [2,2,1,1],
	],
	5 :[
	    [2,1,1,1,1],
	],
	6 :[
	    [1,1,1,1,1,1],
	]
    }
    "3_3": {
	3: [
	    [3,3,3],
	],
	4: [
	    [3,3,2,1],
	    [3,2,2,2],
	],
	5: [
	    [3,3,1,1,1],
	    [3,2,2,1,1],
	    [2,2,2,2,1]
	],
	6: [
	    [3,2,1,1,1,1],
	    [2,2,2,1,1,1],
	]
	7: [
	    [3,1,1,1,1,1,1],
	    [2,2,1,1,1,1,1],
	],
	8: [
	    [2,1,1,1,1,1,1,1]
	],
	9: [
	    [1,1,1,1,1,1,1,1,1]
	]
    },
    "3_4": {
	3: [
	    [4,4,4]
	],
	4: [
	    [4,4,3,1],
	    [4,4,2,2],
	    [4,3,3,2],
	    [3,3,3,3],
	],
	5: [
	    [4,4,2,1,1],
	    [4,3,2,2,1],
	    [4,3,3,1,1],
	    [4,2,2,2,2],
	    [3,3,3,2,1],
	    [3,3,2,2,2],
	]
	6: [
	    [4,4,1,1,1,1],
	    [4,3,2,1,1,1],
	    [4,2,2,2,1,1],
	    [3,3,3,1,1,1],
	    [3,3,2,2,1,1],
	    [3,2,2,2,2,1],
	    [2,2,2,2,2,2],
	],
	7: [
	    [4,3,1,1,1,1,1],
	    [4,2,2,1,1,1,1],
	    [3,3,2,1,1,1,1],
	    [3,2,2,2,1,1,1],
	    [2,2,2,2,2,1,1]
	],
	8: [
	    [4,2,1,1,1,1,1,1],
	    [3,3,1,1,1,1,1,1],
	    [3,2,2,1,1,1,1,1],
	    [2,2,2,2,1,1,1,1],
	],
	9: [
	    [4,1,1,1,1,1,1,1,1],
	    [3,2,1,1,1,1,1,1,1],
	    [2,2,2,1,1,1,1,1,1]
	],
	10: [
	    [3,1,1,1,1,1,1,1,1,1],
	    [2,2,1,1,1,1,1,1,1,1]
	],
	11: [
	    [2,1,1,1,1,1,1,1,1,1,1]
	]
	12: [
	    [1,1,1,1,1,1,1,1,1,1,1,1]
	]
    }
}

----

The json has high level keys like "n_m" where n represents the replica count of
the volume and m represents the distribute count of the volume. under each keys
there are positive numbers as keys, which represent the different possible number
of hosts that can be used to create that mXn volume. Under each integer there is
a list of lists where every list has the possible number of disks in each host.

UI has to validate the user selection of hosts using this json.

=== Alternatives

None

=== Data model impact

None
=== REST API impact

None

=== Security impact

None

=== Notifications/Monitoring impact

None

=== Other end user impact

None

=== Performance Impact

None

=== Other deployer impact

None

=== Developer impact

* This specification has to be followed while adding validation
in UI for volume creation.

== Implementation

=== Assignee(s)

nnDarshan

Primary assignee:
nnDarshan

Other contributors:
  None

=== Work Items

None

== Dependencies

None

== Testing

None

== Documentation Impact

None

== References

None
